import type { Config } from "tailwindcss";

import baseConfig from "@potential/tailwind-config/web";

// export default {
//   // We need to append the path to the UI package to the content array so that
//   // those classes are included correctly.
//   content: [...baseConfig.content, "../../packages/ui/src/*.{ts,tsx}"],
//   presets: [baseConfig],
//   theme: {
//     extend: {
//       fontFamily: {
//         sans: ["var(--font-geist-sans)", ...fontFamily.sans],
//         mono: ["var(--font-geist-mono)", ...fontFamily.mono],
//       },
//     },
//   },
// } satisfies Config;

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  presets: [baseConfig],
  //   safelist: [...tailwindSafelist],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-ibm-plex-sans)"],
        serif: ["var(--font-ibm-plex-serif)"],
      },
      colors: {
        base: {
          1: "var(--sand-1)",
          2: "var(--sand-2)",
          3: "var(--sand-3)",
          4: "var(--sand-4)",
          5: "var(--sand-5)",
          6: "var(--sand-6)",
          7: "var(--sand-7)",
          8: "var(--sand-8)",
          9: "var(--sand-9)",
          10: "var(--sand-10)",
          11: "var(--sand-11)",
          12: "var(--sand-12)",
          a1: "var(--sand-a1)",
          a2: "var(--sand-a2)",
          a3: "var(--sand-a3)",
          a4: "var(--sand-a4)",
          a5: "var(--sand-a5)",
          a6: "var(--sand-a6)",
          a7: "var(--sand-a7)",
          a8: "var(--sand-a8)",
          a9: "var(--sand-a9)",
          a10: "var(--sand-a10)",
          a11: "var(--sand-a11)",
          a12: "var(--sand-a12)",
        },
        orange: {
          1: "var(--orange-1)",
          2: "var(--orange-2)",
          3: "var(--orange-3)",
          4: "var(--orange-4)",
          5: "var(--orange-5)",
          6: "var(--orange-6)",
          7: "var(--orange-7)",
          8: "var(--orange-8)",
          9: "var(--orange-9)",
          10: "var(--orange-10)",
          11: "var(--orange-11)",
          12: "var(--orange-12)",
          a1: "var(--orange-a1)",
          a2: "var(--orange-a2)",
          a3: "var(--orange-a3)",
          a4: "var(--orange-a4)",
          a5: "var(--orange-a5)",
          a6: "var(--orange-a6)",
          a7: "var(--orange-a7)",
          a8: "var(--orange-a8)",
          a9: "var(--orange-a9)",
          a10: "var(--orange-a10)",
          a11: "var(--orange-a11)",
          a12: "var(--orange-a12)",
        },
        blue: {
          1: "var(--blue-1)",
          2: "var(--blue-2)",
          3: "var(--blue-3)",
          4: "var(--blue-4)",
          5: "var(--blue-5)",
          6: "var(--blue-6)",
          7: "var(--blue-7)",
          8: "var(--blue-8)",
          9: "var(--blue-9)",
          10: "var(--blue-10)",
          11: "var(--blue-11)",
          12: "var(--blue-12)",
          a1: "var(--blue-a1)",
          a2: "var(--blue-a2)",
          a3: "var(--blue-a3)",
          a4: "var(--blue-a4)",
          a5: "var(--blue-a5)",
          a6: "var(--blue-a6)",
          a7: "var(--blue-a7)",
          a8: "var(--blue-a8)",
          a9: "var(--blue-a9)",
          a10: "var(--blue-a10)",
          a11: "var(--blue-a11)",
          a12: "var(--blue-a12)",
        },
        sand: {
          1: "var(--sand-1)",
          2: "var(--sand-2)",
          3: "var(--sand-3)",
          4: "var(--sand-4)",
          5: "var(--sand-5)",
          6: "var(--sand-6)",
          7: "var(--sand-7)",
          8: "var(--sand-8)",
          9: "var(--sand-9)",
          10: "var(--sand-10)",
          11: "var(--sand-11)",
          12: "var(--sand-12)",
          a1: "var(--sand-a1)",
          a2: "var(--sand-a2)",
          a3: "var(--sand-a3)",
          a4: "var(--sand-a4)",
          a5: "var(--sand-a5)",
          a6: "var(--sand-a6)",
          a7: "var(--sand-a7)",
          a8: "var(--sand-a8)",
          a9: "var(--sand-a9)",
          a10: "var(--sand-a10)",
          a11: "var(--sand-a11)",
          a12: "var(--sand-a12)",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
