// packages/templates/src/templates/body.ts
import { defineTemplate } from "../utils";

export const consumptionTemplates = {
  "consumption.parent.food": defineTemplate({
    id: "food",
    type: "consumption",
    subType: "consumption.parent.food",
    version: 1,
    name: "Food",
    aiDescriptionHelper:
      "A tracking item to help a user track their food intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "longText",
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.parent.food",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.parent.drink": defineTemplate({
    id: "drink",
    type: "consumption",
    subType: "consumption.parent.drink",
    version: 1,
    name: "Drink",
    aiDescriptionHelper:
      "A tracking item to help a user track their drink intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "longText",
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.parent.drink",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.parent.other": defineTemplate({
    id: "consumptionOther",
    type: "consumption",
    subType: "consumption.parent.other",
    version: 1,
    name: "Other Consumption",
    aiDescriptionHelper:
      "A tracking item to help a user track their other consumption",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "longText",
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.parent.other",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.protein": defineTemplate({
    id: "protein",
    type: "consumption",
    subType: "consumption.macros.protein",
    version: 1,
    name: "Protein",
    aiDescriptionHelper:
      "A tracking item to help a user track their protein intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.protein",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.carbs": defineTemplate({
    id: "carbs",
    type: "consumption",
    subType: "consumption.macros.carbs",
    version: 1,
    name: "Carbs",
    aiDescriptionHelper:
      "A tracking item to help a user track their carbs intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.carbs",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.fat": defineTemplate({
    id: "fat",
    type: "consumption",
    subType: "consumption.macros.fat",
    version: 1,
    name: "Fat",
    aiDescriptionHelper:
      "A tracking item to help a user track their fat intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.fat",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.fatSaturated": defineTemplate({
    id: "fatSaturated",
    type: "consumption",
    subType: "consumption.macros.fatSaturated",
    version: 1,
    name: "Saturated Fat",
    aiDescriptionHelper:
      "A tracking item to help a user track their saturated fat intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.fatSaturated",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.fatMonounsaturated": defineTemplate({
    id: "fatMonounsaturated",
    type: "consumption",
    subType: "consumption.macros.fatMonounsaturated",
    version: 1,
    name: "Monounsaturated Fat",
    aiDescriptionHelper:
      "A tracking item to help a user track their monounsaturated fat intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.fatMonounsaturated",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.fatPolyunsaturated": defineTemplate({
    id: "fatPolyunsaturated",
    type: "consumption",
    subType: "consumption.macros.fatPolyunsaturated",
    version: 1,
    name: "Polyunsaturated Fat",
    aiDescriptionHelper:
      "A tracking item to help a user track their polyunsaturated fat intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.fatPolyunsaturated",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.fatTrans": defineTemplate({
    id: "fatTrans",
    type: "consumption",
    subType: "consumption.macros.fatTrans",
    version: 1,
    name: "Trans Fat",
    aiDescriptionHelper:
      "A tracking item to help a user track their trans fat intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.fatTrans",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.cholesterol": defineTemplate({
    id: "cholesterol",
    type: "consumption",
    subType: "consumption.macros.cholesterol",
    version: 1,
    name: "Cholesterol",
    aiDescriptionHelper:
      "A tracking item to help a user track their cholesterol intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.cholesterol",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.sugar": defineTemplate({
    id: "sugar",
    type: "consumption",
    subType: "consumption.macros.sugar",
    version: 1,
    name: "Sugar",
    aiDescriptionHelper:
      "A tracking item to help a user track their sugar intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.sugar",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.sugarAdded": defineTemplate({
    id: "sugarAdded",
    type: "consumption",
    subType: "consumption.macros.sugarAdded",
    version: 1,
    name: "Added Sugar",
    aiDescriptionHelper:
      "A tracking item to help a user track their added sugar intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.sugarAdded",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.sugarNatural": defineTemplate({
    id: "sugarNatural",
    type: "consumption",
    subType: "consumption.macros.sugarNatural",
    version: 1,
    name: "Natural Sugar",
    aiDescriptionHelper:
      "A tracking item to help a user track their natural sugar intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.sugarNatural",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.fiber": defineTemplate({
    id: "fiber",
    type: "consumption",
    subType: "consumption.macros.fiber",
    version: 1,
    name: "Fiber",
    aiDescriptionHelper:
      "A tracking item to help a user track their fiber intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.fiber",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.water": defineTemplate({
    id: "water",
    type: "consumption",
    subType: "consumption.macros.water",
    version: 1,
    name: "Water",
    aiDescriptionHelper:
      "A tracking item to help a user track their water intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "volume",
      measureUnitSource: "ml",
      measureUnitDisplay: "ml",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.water",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.alcohol": defineTemplate({
    id: "alcohol",
    type: "consumption",
    subType: "consumption.macros.alcohol",
    version: 1,
    name: "Alcohol",
    aiDescriptionHelper:
      "A tracking item to help a user track their alcohol intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "g",
      measureUnitDisplay: "g",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.alcohol",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.macros.caffeine": defineTemplate({
    id: "caffeine",
    type: "consumption",
    subType: "consumption.macros.caffeine",
    version: 1,
    name: "Caffeine",
    aiDescriptionHelper:
      "A tracking item to help a user track their caffeine intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.macros.caffeine",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.sodium": defineTemplate({
    id: "sodium",
    type: "consumption",
    subType: "consumption.minerals.sodium",
    version: 1,
    name: "Sodium",
    aiDescriptionHelper:
      "A tracking item to help a user track their sodium intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.sodium",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.magnesium": defineTemplate({
    id: "magnesium",
    type: "consumption",
    subType: "consumption.minerals.magnesium",
    version: 1,
    name: "Magnesium",
    aiDescriptionHelper:
      "A tracking item to help a user track their magnesium intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.magnesium",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.calcium": defineTemplate({
    id: "calcium",
    type: "consumption",
    subType: "consumption.minerals.calcium",
    version: 1,
    name: "Calcium",
    aiDescriptionHelper:
      "A tracking item to help a user track their calcium intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.calcium",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.iron": defineTemplate({
    id: "iron",
    type: "consumption",
    subType: "consumption.minerals.iron",
    version: 1,
    name: "Iron",
    aiDescriptionHelper:
      "A tracking item to help a user track their iron intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.iron",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.zinc": defineTemplate({
    id: "zinc",
    type: "consumption",
    subType: "consumption.minerals.zinc",
    version: 1,
    name: "Zinc",
    aiDescriptionHelper:
      "A tracking item to help a user track their zinc intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.zinc",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.potassium": defineTemplate({
    id: "potassium",
    type: "consumption",
    subType: "consumption.minerals.potassium",
    version: 1,
    name: "Potassium",
    aiDescriptionHelper:
      "A tracking item to help a user track their potassium intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.potassium",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.copper": defineTemplate({
    id: "copper",
    type: "consumption",
    subType: "consumption.minerals.copper",
    version: 1,
    name: "Copper",
    aiDescriptionHelper:
      "A tracking item to help a user track their copper intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.copper",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.manganese": defineTemplate({
    id: "manganese",
    type: "consumption",
    subType: "consumption.minerals.manganese",
    version: 1,
    name: "Manganese",
    aiDescriptionHelper:
      "A tracking item to help a user track their manganese intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.manganese",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.selenium": defineTemplate({
    id: "selenium",
    type: "consumption",
    subType: "consumption.minerals.selenium",
    version: 1,
    name: "Selenium",
    aiDescriptionHelper:
      "A tracking item to help a user track their selenium intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.selenium",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.phosphorus": defineTemplate({
    id: "phosphorus",
    type: "consumption",
    subType: "consumption.minerals.phosphorus",
    version: 1,
    name: "Phosphorus",
    aiDescriptionHelper:
      "A tracking item to help a user track their phosphorus intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.phosphorus",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.chromium": defineTemplate({
    id: "chromium",
    type: "consumption",
    subType: "consumption.minerals.chromium",
    version: 1,
    name: "Chromium",
    aiDescriptionHelper:
      "A tracking item to help a user track their chromium intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.chromium",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.iodine": defineTemplate({
    id: "iodine",
    type: "consumption",
    subType: "consumption.minerals.iodine",
    version: 1,
    name: "Iodine",
    aiDescriptionHelper:
      "A tracking item to help a user track their iodine intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.iodine",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.molybdenum": defineTemplate({
    id: "molybdenum",
    type: "consumption",
    subType: "consumption.minerals.molybdenum",
    version: 1,
    name: "Molybdenum",
    aiDescriptionHelper:
      "A tracking item to help a user track their molybdenum intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.molybdenum",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.chloride": defineTemplate({
    id: "chloride",
    type: "consumption",
    subType: "consumption.minerals.chloride",
    version: 1,
    name: "Chloride",
    aiDescriptionHelper:
      "A tracking item to help a user track their chloride intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.chloride",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.fluoride": defineTemplate({
    id: "fluoride",
    type: "consumption",
    subType: "consumption.minerals.fluoride",
    version: 1,
    name: "Fluoride",
    aiDescriptionHelper:
      "A tracking item to help a user track their fluoride intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.fluoride",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.minerals.sulfur": defineTemplate({
    id: "sulfur",
    type: "consumption",
    subType: "consumption.minerals.sulfur",
    version: 1,
    name: "Sulfur",
    aiDescriptionHelper:
      "A tracking item to help a user track their sulfur intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.minerals.sulfur",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.A": defineTemplate({
    id: "A",
    type: "consumption",
    subType: "consumption.vitamins.A",
    version: 1,
    name: "Vitamin A",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin A intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.A",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.B1": defineTemplate({
    id: "B1",
    type: "consumption",
    subType: "consumption.vitamins.B1",
    version: 1,
    name: "Vitamin B1",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin B1 intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.B1",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.B2": defineTemplate({
    id: "B2",
    type: "consumption",
    subType: "consumption.vitamins.B2",
    version: 1,
    name: "Vitamin B2",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin B2 intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.B2",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.B3": defineTemplate({
    id: "B3",
    type: "consumption",
    subType: "consumption.vitamins.B3",
    version: 1,
    name: "Vitamin B3",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin B3 intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.B3",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.B5": defineTemplate({
    id: "B5",
    type: "consumption",
    subType: "consumption.vitamins.B5",
    version: 1,
    name: "Vitamin B5",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin B5 intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.B5",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.B6": defineTemplate({
    id: "B6",
    type: "consumption",
    subType: "consumption.vitamins.B6",
    version: 1,
    name: "Vitamin B6",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin B6 intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.B6",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.B7": defineTemplate({
    id: "B7",
    type: "consumption",
    subType: "consumption.vitamins.B7",
    version: 1,
    name: "Vitamin B7",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin B7 intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.B7",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.B9": defineTemplate({
    id: "B9",
    type: "consumption",
    subType: "consumption.vitamins.B9",
    version: 1,
    name: "Vitamin B9",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin B9 intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.B9",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.B12": defineTemplate({
    id: "B12",
    type: "consumption",
    subType: "consumption.vitamins.B12",
    version: 1,
    name: "Vitamin B12",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin B12 intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.B12",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.C": defineTemplate({
    id: "C",
    type: "consumption",
    subType: "consumption.vitamins.C",
    version: 1,
    name: "Vitamin C",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin C intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.C",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.D": defineTemplate({
    id: "D",
    type: "consumption",
    subType: "consumption.vitamins.D",
    version: 1,
    name: "Vitamin D",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin D intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.D",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.E": defineTemplate({
    id: "E",
    type: "consumption",
    subType: "consumption.vitamins.E",
    version: 1,
    name: "Vitamin E",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin E intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "mg",
      measureUnitDisplay: "mg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.E",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
  "consumption.vitamins.K": defineTemplate({
    id: "K",
    type: "consumption",
    subType: "consumption.vitamins.K",
    version: 1,
    name: "Vitamin K",
    aiDescriptionHelper:
      "A tracking item to help a user track their vitamin K intake",
    recommended: true,
    featured: true,
    uses: 0,
    defaultConfig: {
      type: "measure",
      measureUnitType: "mass",
      measureUnitSource: "µg",
      measureUnitDisplay: "µg",
      measureTarget: null,
      cumulative: true,
      limitOnePerDay: false,
      _meta: {
        templateId: "consumption.vitamins.K",
        templateVersion: 1,
        isCustomized: false,
      },
    },
  }),
};
